create table "public"."appraisal_answers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "answers" jsonb[] not null default '{}'::jsonb[],
    "contract" bigint not null,
    "is_submitted" boolean not null default false,
    "group" text not null,
    "date" date not null,
    "org" text,
    "entity" bigint
);


alter table "public"."appraisal_answers" enable row level security;

create table "public"."appraisal_settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "frequency" text not null,
    "start_date" date,
    "org" text not null,
    "entity" bigint
);


alter table "public"."appraisal_settings" enable row level security;

alter table "public"."appraisal_questions" add column "order" smallint not null default '0'::smallint;

CREATE UNIQUE INDEX appraisal_answers_pkey ON public.appraisal_answers USING btree (id);

CREATE UNIQUE INDEX appraisal_settings_org_key ON public.appraisal_settings USING btree (org);

CREATE UNIQUE INDEX appraisal_settings_pkey ON public.appraisal_settings USING btree (id);

alter table "public"."appraisal_answers" add constraint "appraisal_answers_pkey" PRIMARY KEY using index "appraisal_answers_pkey";

alter table "public"."appraisal_settings" add constraint "appraisal_settings_pkey" PRIMARY KEY using index "appraisal_settings_pkey";

alter table "public"."appraisal_answers" add constraint "appraisal_answers_contract_fkey" FOREIGN KEY (contract) REFERENCES contracts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."appraisal_answers" validate constraint "appraisal_answers_contract_fkey";

alter table "public"."appraisal_answers" add constraint "appraisal_answers_entity_fkey" FOREIGN KEY (entity) REFERENCES legal_entities(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."appraisal_answers" validate constraint "appraisal_answers_entity_fkey";

alter table "public"."appraisal_answers" add constraint "appraisal_answers_org_fkey" FOREIGN KEY (org) REFERENCES organisations(subdomain) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."appraisal_answers" validate constraint "appraisal_answers_org_fkey";

alter table "public"."appraisal_settings" add constraint "appraisal_settings_entity_fkey" FOREIGN KEY (entity) REFERENCES legal_entities(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."appraisal_settings" validate constraint "appraisal_settings_entity_fkey";

alter table "public"."appraisal_settings" add constraint "appraisal_settings_org_fkey" FOREIGN KEY (org) REFERENCES organisations(subdomain) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."appraisal_settings" validate constraint "appraisal_settings_org_fkey";

alter table "public"."appraisal_settings" add constraint "appraisal_settings_org_key" UNIQUE using index "appraisal_settings_org_key";

grant delete on table "public"."appraisal_answers" to "anon";

grant insert on table "public"."appraisal_answers" to "anon";

grant references on table "public"."appraisal_answers" to "anon";

grant select on table "public"."appraisal_answers" to "anon";

grant trigger on table "public"."appraisal_answers" to "anon";

grant truncate on table "public"."appraisal_answers" to "anon";

grant update on table "public"."appraisal_answers" to "anon";

grant delete on table "public"."appraisal_answers" to "authenticated";

grant insert on table "public"."appraisal_answers" to "authenticated";

grant references on table "public"."appraisal_answers" to "authenticated";

grant select on table "public"."appraisal_answers" to "authenticated";

grant trigger on table "public"."appraisal_answers" to "authenticated";

grant truncate on table "public"."appraisal_answers" to "authenticated";

grant update on table "public"."appraisal_answers" to "authenticated";

grant delete on table "public"."appraisal_answers" to "service_role";

grant insert on table "public"."appraisal_answers" to "service_role";

grant references on table "public"."appraisal_answers" to "service_role";

grant select on table "public"."appraisal_answers" to "service_role";

grant trigger on table "public"."appraisal_answers" to "service_role";

grant truncate on table "public"."appraisal_answers" to "service_role";

grant update on table "public"."appraisal_answers" to "service_role";

grant delete on table "public"."appraisal_settings" to "anon";

grant insert on table "public"."appraisal_settings" to "anon";

grant references on table "public"."appraisal_settings" to "anon";

grant select on table "public"."appraisal_settings" to "anon";

grant trigger on table "public"."appraisal_settings" to "anon";

grant truncate on table "public"."appraisal_settings" to "anon";

grant update on table "public"."appraisal_settings" to "anon";

grant delete on table "public"."appraisal_settings" to "authenticated";

grant insert on table "public"."appraisal_settings" to "authenticated";

grant references on table "public"."appraisal_settings" to "authenticated";

grant select on table "public"."appraisal_settings" to "authenticated";

grant trigger on table "public"."appraisal_settings" to "authenticated";

grant truncate on table "public"."appraisal_settings" to "authenticated";

grant update on table "public"."appraisal_settings" to "authenticated";

grant delete on table "public"."appraisal_settings" to "service_role";

grant insert on table "public"."appraisal_settings" to "service_role";

grant references on table "public"."appraisal_settings" to "service_role";

grant select on table "public"."appraisal_settings" to "service_role";

grant trigger on table "public"."appraisal_settings" to "service_role";

grant truncate on table "public"."appraisal_settings" to "service_role";

grant update on table "public"."appraisal_settings" to "service_role";

create policy "Enable all for authenticated users only"
on "public"."appraisal_answers"
as permissive
for all
to authenticated
using (true);


create policy "Enable all for authenticated users only"
on "public"."appraisal_settings"
as permissive
for all
to authenticated
using (true);



