create table "public"."appraisal_history" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "org" text not null,
    "entity" bigint,
    "group" text not null,
    "start_date" date not null default now(),
    "end_date" date not null
);


alter table "public"."appraisal_history" enable row level security;

alter table "public"."appraisal_settings" add column "timeline" smallint not null default '2'::smallint;

CREATE UNIQUE INDEX appraisal_history_pkey ON public.appraisal_history USING btree (id);

alter table "public"."appraisal_history" add constraint "appraisal_history_pkey" PRIMARY KEY using index "appraisal_history_pkey";

alter table "public"."appraisal_history" add constraint "appraisal_history_entity_fkey" FOREIGN KEY (entity) REFERENCES legal_entities(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."appraisal_history" validate constraint "appraisal_history_entity_fkey";

alter table "public"."appraisal_history" add constraint "appraisal_history_org_fkey" FOREIGN KEY (org) REFERENCES organisations(subdomain) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."appraisal_history" validate constraint "appraisal_history_org_fkey";

grant delete on table "public"."appraisal_history" to "anon";

grant insert on table "public"."appraisal_history" to "anon";

grant references on table "public"."appraisal_history" to "anon";

grant select on table "public"."appraisal_history" to "anon";

grant trigger on table "public"."appraisal_history" to "anon";

grant truncate on table "public"."appraisal_history" to "anon";

grant update on table "public"."appraisal_history" to "anon";

grant delete on table "public"."appraisal_history" to "authenticated";

grant insert on table "public"."appraisal_history" to "authenticated";

grant references on table "public"."appraisal_history" to "authenticated";

grant select on table "public"."appraisal_history" to "authenticated";

grant trigger on table "public"."appraisal_history" to "authenticated";

grant truncate on table "public"."appraisal_history" to "authenticated";

grant update on table "public"."appraisal_history" to "authenticated";

grant delete on table "public"."appraisal_history" to "service_role";

grant insert on table "public"."appraisal_history" to "service_role";

grant references on table "public"."appraisal_history" to "service_role";

grant select on table "public"."appraisal_history" to "service_role";

grant trigger on table "public"."appraisal_history" to "service_role";

grant truncate on table "public"."appraisal_history" to "service_role";

grant update on table "public"."appraisal_history" to "service_role";

create policy "Enable all for authenticated users only"
on "public"."appraisal_history"
as permissive
for all
to authenticated
using (true);



