create table "public"."appraisal_questions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "question" text not null,
    "org" text not null,
    "entity" bigint,
    "options" jsonb[] not null,
    "type" text not null,
    "required" boolean not null default false,
    "group" text not null
);


alter table "public"."appraisal_questions" enable row level security;

CREATE UNIQUE INDEX appraisal_questions_pkey ON public.appraisal_questions USING btree (id);

alter table "public"."appraisal_questions" add constraint "appraisal_questions_pkey" PRIMARY KEY using index "appraisal_questions_pkey";

alter table "public"."appraisal_questions" add constraint "appraisal_questions_entity_fkey" FOREIGN KEY (entity) REFERENCES legal_entities(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."appraisal_questions" validate constraint "appraisal_questions_entity_fkey";

alter table "public"."appraisal_questions" add constraint "appraisal_questions_org_fkey" FOREIGN KEY (org) REFERENCES organisations(subdomain) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."appraisal_questions" validate constraint "appraisal_questions_org_fkey";

grant delete on table "public"."appraisal_questions" to "anon";

grant insert on table "public"."appraisal_questions" to "anon";

grant references on table "public"."appraisal_questions" to "anon";

grant select on table "public"."appraisal_questions" to "anon";

grant trigger on table "public"."appraisal_questions" to "anon";

grant truncate on table "public"."appraisal_questions" to "anon";

grant update on table "public"."appraisal_questions" to "anon";

grant delete on table "public"."appraisal_questions" to "authenticated";

grant insert on table "public"."appraisal_questions" to "authenticated";

grant references on table "public"."appraisal_questions" to "authenticated";

grant select on table "public"."appraisal_questions" to "authenticated";

grant trigger on table "public"."appraisal_questions" to "authenticated";

grant truncate on table "public"."appraisal_questions" to "authenticated";

grant update on table "public"."appraisal_questions" to "authenticated";

grant delete on table "public"."appraisal_questions" to "service_role";

grant insert on table "public"."appraisal_questions" to "service_role";

grant references on table "public"."appraisal_questions" to "service_role";

grant select on table "public"."appraisal_questions" to "service_role";

grant trigger on table "public"."appraisal_questions" to "service_role";

grant truncate on table "public"."appraisal_questions" to "service_role";

grant update on table "public"."appraisal_questions" to "service_role";

create policy "Enable all for authenticated users only"
on "public"."appraisal_questions"
as permissive
for all
to authenticated
using (true);



