'use client';

export { StarterKit } from '@tiptap/starter-kit';
export { Highlight } from '@tiptap/extension-highlight';
// export { CharacterCount } from '@tiptap/extension-character-count';
export { Underline } from '@tiptap/extension-underline';
export { Placeholder } from '@tiptap/extension-placeholder';
// export { Emoji, gitHubEmojis } from '@tiptap-pro/extension-emoji';
export { TextAlign } from '@tiptap/extension-text-align';
export { TextStyle } from '@tiptap/extension-text-style';
export { Typography } from '@tiptap/extension-typography';
export { Color } from '@tiptap/extension-color';
export { FocusClasses as Focus } from '@tiptap/extension-focus';
export { Dropcursor } from '@tiptap/extension-dropcursor';
export { Subscript } from '@tiptap/extension-subscript';
export { Superscript } from '@tiptap/extension-superscript';
export { Paragraph } from '@tiptap/extension-paragraph';
export { BulletList } from '@tiptap/extension-bullet-list';
export { OrderedList } from '@tiptap/extension-ordered-list';
// export { UniqueID } from '@tiptap-pro/extension-unique-id';
// export { FileHandler } from '@tiptap-pro/extension-file-handler';

export { Selection } from './Selection';
export { HorizontalRule } from './HorizontalRule';
// export { Heading } from './Heading';
export { TrailingNode } from './TrailingNode';
export { SlashCommand } from './SlashCommand';
export { FontSize } from './FontSize';
export { Figure } from './Figure';
// export { Figcaption } from './Figcaption';
export { BlockquoteFigure } from './BlockquoteFigure';
export { SignatureFigure } from './Signature';
export { Quote } from './BlockquoteFigure/Quote';
export { QuoteCaption } from './BlockquoteFigure/QuoteCaption';
export { Link } from './Link';
export { ImageUpload } from './ImageUpload';
export { ImageBlock } from './ImageBlock';
export { emojiSuggestion } from './EmojiSuggestion';

// export { Details } from '@tiptap-pro/extension-details';
// export { DetailsContent } from '@tiptap-pro/extension-details-content';
// export { DetailsSummary } from '@tiptap-pro/extension-details-summary';
// export { TableOfContents } from '@tiptap-pro/extension-table-of-contents';
export { Table, TableCell, TableHeader, TableRow } from './Table';
export { Document } from './Document';
export { Mention } from '@tiptap/extension-mention';
export { SignatureImage } from './SignatureImage';
